[[aws_c_iot]]
arch = "aarch64"
git-tree-sha1 = "b84b69ec35bdafc92144910ef2b076aa494c3368"
os = "macos"

    [[aws_c_iot.download]]
    sha256 = "8ba884ec5daf920e5e8c6c49faf0f32f07c5fef633123ca20414b35a3ce0c60b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.aarch64-apple-darwin.tar.gz"
[[aws_c_iot]]
arch = "aarch64"
git-tree-sha1 = "6515bd2339fb1160a6581beae442a8851cae3beb"
libc = "glibc"
os = "linux"

    [[aws_c_iot.download]]
    sha256 = "5797918c0e812ad5239fd8f28b964d9468fa94994a20c58a7b164aed6346d3bf"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.aarch64-linux-gnu.tar.gz"
[[aws_c_iot]]
arch = "aarch64"
git-tree-sha1 = "63c53d8698ec53c67f142fa64fe734b94d91963c"
libc = "musl"
os = "linux"

    [[aws_c_iot.download]]
    sha256 = "f9c79167d45ed2834397f9e3f1de9509734955c5d23fc1d9df668de9bab05b47"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.aarch64-linux-musl.tar.gz"
[[aws_c_iot]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9d823d3944c9fdd39fc536818cc489e6c10920e2"
libc = "glibc"
os = "linux"

    [[aws_c_iot.download]]
    sha256 = "bddac630d53aff19f450091c09f4f8f097b9cacefce230968507c30577e513ac"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_iot]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d660432ca3eb05fb68f2800926a594d33f0a06d"
libc = "musl"
os = "linux"

    [[aws_c_iot.download]]
    sha256 = "8f7cf4cedeae382a535eb69e0fc6a7c14308650a432be883d6d90c682e00310d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.armv6l-linux-musleabihf.tar.gz"
[[aws_c_iot]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "03cfa974abe9b2fd669e032fe72c994134cc8e20"
libc = "glibc"
os = "linux"

    [[aws_c_iot.download]]
    sha256 = "37de81a7a334468dce3d48349528b5bc7a002dca83e126c0288595ebd4fd344e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_iot]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bd10d7e4eba35c44416e25b3f4a95f9dd39b5844"
libc = "musl"
os = "linux"

    [[aws_c_iot.download]]
    sha256 = "08c261ab47710d70119243db8694a88634c91760621bad8cff2a7d55362d6e53"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.armv7l-linux-musleabihf.tar.gz"
[[aws_c_iot]]
arch = "i686"
git-tree-sha1 = "49df5be1fd92a415c6ab5cbcbf04ef3191f78ece"
libc = "glibc"
os = "linux"

    [[aws_c_iot.download]]
    sha256 = "50f3abd99ac2d6762a83dfea276bc525301301f52fac9f95ba169749ca604ba7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.i686-linux-gnu.tar.gz"
[[aws_c_iot]]
arch = "i686"
git-tree-sha1 = "22d95c9ab8a70251894e80d568260d55fbd572d5"
libc = "musl"
os = "linux"

    [[aws_c_iot.download]]
    sha256 = "8b749864448d36f03b48351fead6d6749fe6abd329d3142095bbac110aac0d74"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.i686-linux-musl.tar.gz"
[[aws_c_iot]]
arch = "powerpc64le"
git-tree-sha1 = "f2b08518258d5529900f0b9d9395e9e243c6d71e"
libc = "glibc"
os = "linux"

    [[aws_c_iot.download]]
    sha256 = "ac4ebe04e37aa8cbb777506c121edb7b2f6c2397ea4248cecd60720cec897fd4"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.powerpc64le-linux-gnu.tar.gz"
[[aws_c_iot]]
arch = "x86_64"
git-tree-sha1 = "64259b62127704492e46ce89c7bb7c528506f0b3"
os = "macos"

    [[aws_c_iot.download]]
    sha256 = "d72ad0aed1676ad8629368b7dd4589c900340be07f963401ce1fb384854971a5"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.x86_64-apple-darwin.tar.gz"
[[aws_c_iot]]
arch = "x86_64"
git-tree-sha1 = "701ab473405feef5eefcd4757aa209ca22c5d6f6"
libc = "glibc"
os = "linux"

    [[aws_c_iot.download]]
    sha256 = "9356598385bd2524c82ab798f22220968644d21daeb129bb34db8f783a17ae42"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.x86_64-linux-gnu.tar.gz"
[[aws_c_iot]]
arch = "x86_64"
git-tree-sha1 = "860d1ee03efee33877e5c4d35f663d069a777fb0"
libc = "musl"
os = "linux"

    [[aws_c_iot.download]]
    sha256 = "1b87fb8f743ca56d6a128deb388e2278c626a6e8517b6ce08959d7832fd605b7"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.x86_64-linux-musl.tar.gz"
[[aws_c_iot]]
arch = "x86_64"
git-tree-sha1 = "515d1a6ac5876783efaea0c716fef51726f54c55"
os = "freebsd"

    [[aws_c_iot.download]]
    sha256 = "a8701df0b0dfc59aef21722169f14e415a8de021765ccc3fae66fe47124a172d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.x86_64-unknown-freebsd.tar.gz"
[[aws_c_iot]]
arch = "x86_64"
git-tree-sha1 = "40fe9ee9d40c3422e092077d49330e54e35a3d6b"
os = "windows"

    [[aws_c_iot.download]]
    sha256 = "72534ac59e418dc88bdd1e72f9f2921a9646e4dd912f51f604667bb83b0702a1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_iot_jll.jl/releases/download/aws_c_iot-v0.1.21+0/aws_c_iot.v0.1.21.x86_64-w64-mingw32.tar.gz"
