# Autogenerated wrapper script for aws_c_iot_jll for armv6l-linux-gnueabihf
export libaws_c_iot

using aws_c_mqtt_jll
JLLWrappers.@generate_wrapper_header("aws_c_iot")
JLLWrappers.@declare_library_product(libaws_c_iot, "libaws-c-iot.so.0unstable")
function __init__()
    JLLWrappers.@generate_init_header(aws_c_mqtt_jll)
    JLLWrappers.@init_library_product(
        libaws_c_iot,
        "lib/libaws-c-iot.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
