# Autogenerated wrapper script for aws_c_iot_jll for x86_64-apple-darwin
export libaws_c_iot

using aws_c_mqtt_jll
JLLWrappers.@generate_wrapper_header("aws_c_iot")
JLLWrappers.@declare_library_product(libaws_c_iot, "@rpath/libaws-c-iot.0unstable.dylib")
function __init__()
    JLLWrappers.@generate_init_header(aws_c_mqtt_jll)
    JLLWrappers.@init_library_product(
        libaws_c_iot,
        "lib/libaws-c-iot.1.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
